[common-etcd]
host = "etcd:2379"
basePath = "/gochat_srv"
serverPathLogic = "LogicRpc"
serverPathConnect = "ConnectRpc"
userName = ""
password = ""
connectionTimeout = 5

[common-redis]
redisAddress = "redis:6379"
redisPassword = ""
db = 0

[common-rabbitmq]
url = "amqp://gochat:gochat_secret@rabbitmq:5672/gochat"
prefetchCount = 10

[common-tracing]
enabled = true
endpoint = "jaeger:4318"
samplingRate = 0.1